#!/bin/bash

remote_server=$1
remote_port=$2
local_port=$3

# Keep long connection 
#   TCPKeepAlive=yes 
#   ServerAliveInterval=30
# Don't indenify the remote host
#   UserKnownHostsFile=/dev/null
#   StrictHostKeyChecking=no
ssh -v \
    -o TCPKeepAlive=yes \
    -o ServerAliveInterval=30 \
    -o UserKnownHostsFile=/dev/null \
    -o StrictHostKeyChecking=no \
    -p 7878 channel@${remote_server} -N -R ${remote_port}:localhost:${local_port}
